Add uploading models method for MODAC client
mass-matrix/AMPL pull request #51
Opened 2024-08-01 20:27 UTC by andriialbatov

2024-08-01 20:28 UTC, andriialbatov commented
![Screenshot 2024-08-01 at 4 27 51 PM](https://github.com/user-attachments/assets/eb96063d-6801-40bd-a8b3-dfd27cd60c81)

2024-08-05 15:10 UTC, Kartstig requested changes
I'd like to fix the code around file closing

2024-08-05 15:10 UTC, Kartstig commented on atomsci/modac/__init__.py
> +            raise
```suggestion
            raise e
```
It's good practice to raise the previous exception unless you have a custom one to raise

We could make our own custom exception for this module but that might not be necessary yet

2024-08-05 15:10 UTC, Kartstig commented on atomsci/modac/__init__.py
> +                open(data_file_path, "rb"),
I think your code works for 99.99% of the time, but let's say `_logger.warning` encountered a runtime error. This file would remain open. You were correct in using `finally` to catch for most error cases. However, I think it's just best practice to use the `with open(...) as f` syntax, and then you don't have to worry or think about closing:


```python
with open(data_file_path, "rb") as f:
    ...
```

2024-08-05 16:42 UTC, Kartstig approved these changes

2024-08-05 16:42 UTC, merged